/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xe.h"
#include "stm32f4xx.h"

void init_app(void);
void init_tim3(void);

int main(void)
{
    init_app(); //LLAMAR A LAS FUNCIONES DE INICIALIZACION

    init_tim3(); //LLAMAR A LAS FUNCIONES DE INICIALIZACION DEL TIM3

    while(1){

    }

    return 0;
}

void init_app(){
    //RCC->AHB1ENR &= ~(1<<0);
    RCC->AHB1ENR &= ~RCC_AHB1ENR_GPIOAEN; // limpiando la posicion
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; // activando la señal

    //configurando el pin 5
    GPIOA->MODER &= ~(GPIO_MODER_MODE5); // limpiando la posición
    GPIOA->MODER |= (GPIO_MODER_MODE5_0); // configurando como salida

    GPIOA->OTYPER &= ~GPIO_OTYPER_OT5; // configurando como push-pull

    GPIOA->OSPEEDR &= ~(GPIO_OSPEEDR_OSPEED5); // LIMPIANDO LA POSICION
    GPIOA->OSPEEDR |= (GPIO_OSPEEDR_OSPEED5_1 | GPIO_OSPEEDR_OSPEED5_0); // configurando la velocidad

    GPIOA->ODR |= (GPIO_ODR_OD5); // encendiendo el led
}


void init_tim3(){
    // señal del rekij para el tim 3

    RCC->APB1ENR &= ~RCC_APB1ENR_TIM3EN; // LIMPIANDO LA SEÑAL DEL TIM3
    RCC->APB1ENR |= RCC_APB1ENR_TIM3EN; // ACTIVANDO LA SEÑAL DEL TIM3  

    TIM3->CNT = 0; // reiniciando el contador
    TIM3->PSC = (1600 -1); // DIVISOR POR 1600
    TIM3->ARR = (2500 -1); // valor de recarga

    TIM3->CR1 &= ~(0X3 << TIM_CR1_CMS_Pos); // LIMPIAMOS DEJAR LA SEÑAL DE RELOJ (Opcional)
    TIM3->CR1 &= ~(TIM_CR1_DIR); // LIMPIAMOS LA POSICION
    TIM3->CR1 &= ~(TIM_CR1_ARPE); // ACTIVANDO EL PRELOAD PARA EL ARR
    TIM3->CR1 |= (TIM_CR1_DIR); // configurando el contador en modo ascendente
    TIM3->CR1 &= ~TIM_CR1_CEN; // LIMPIANDO

    TIM3->DIER |= TIM_DIER_UIE; // habilitando la interrupcion del tim3

    //configurando la el INVIC
    __NVIC_EnableIRQ(TIM3_IRQn); // habilitando la interrupcion del tim3

    TIM3->CR1 |= TIM_CR1_CEN; // activando el contador
}

void TIM3_IRQHandler(void){
    // Verificando si la bandera de interrupción está activa
    if(TIM3->SR & TIM_SR_UIF){
        TIM3->SR &= ~TIM_SR_UIF; // LIMPIANDO LA BANDERA
        GPIOA->ODR ^= GPIO_ODR_OD5; // CAMBIANDO EL ESTADO DEL LED
    }
}

